### ISSUE TITLE
Add sync/modify to Kokkos memory events

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#11]
It would be nice if the memory events output could include sync/modify between different memory spaces, since this is a memory event. Right now the tool seems to only include allocate and deallocate.

**Comment by ibaned** [comment]
I'm trying to get a sense of what the end goal is here, in terms of a profiling report. Would it be, for example, the number of `deep_copy` calls that are actually made? I can see that being useful performance data, but I'm not sure what one would do with `sync` and `modify`.

**Comment by stanmoore1** [comment]
@ibaned I'm trying to track memory movement between host and device. If I have unnecessary deep copies then that can really hurt performance, so yes tracking deep copies and including the source and destination memory spaces would be helpful. I can get this same info from `nvprof` so perhaps this can be lower priority, but it would be nice.

**Comment by ibaned** [comment]
This is another thing that would need to be implemented in Kokkos first. I created kokkos/kokkos#843 for it.

If you like what you get from `nvprof`, maybe post it here for inpiration for future `kokkos-tools`. Or you have an idea for a better report format, thats even better.

**Comment by stanmoore1** [comment]
The way I track it now is putting `printf` statements in Kokkos_DualView.hpp. However, that only works if you use `dual views` exclusively.

**Comment by ibaned** [comment]
#17 (which was merged into master just now) and kokkos/kokkos#893 (which is pending review to get into develop) will add `deep_copy` as a parallel construct that gets timed just like `parallel_for`. It will show up in the time tree reports, with the name being `"destination_label"="source_label"`.

**Comment by ibaned** [comment]
The Kokkos support is in develop.

**Comment by stanmoore1** [comment]
`deep_copy` parallel constructs were added in #17, closing this issue.
