### ISSUE TITLE
Make Simple Kernel Timer Split out Tagged Parallel Loops

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#14]
When using `tags` instead of `functors` or `lambdas`, the simple kernel timer aggregates all of the time spent in all the `tags` in each class into one category. It should instead give separate timings for each `tag` individually.

**Comment by stanmoore1** [comment]
It seems to work if I add labels to all of the parallel loops. It would be nice if it just used the `tag` as the label instead of having to manually duplicate the `tag` as the label.

**Comment by ibaned** [comment]
This can't be done from `kokkos-tools`, it needs to be done in Kokkos itself. I created kokkos/kokkos#842 to track it there, we can close this one if thats okay.

**Comment by stanmoore1** [comment]
@ibaned yes closed #14.
