### ISSUE TITLE
Warning in roctx-connector

### ISSUE THREAD

**Issue by jhux2** [kokkos/kokkos-tools#143]
Using ROCM 5.2.0, compiling the roctx connector gives a warning:
```
g++ -shared -fPIC -O3 -g -I/opt/rocm-5.2.0/roctracer/include -I/autofs/nccs-svm1_home1/jjhu/crusher/kokkos-tools/src/kokkos-tools/profiling/roctx-connector/ -L/opt/rocm-5.2.0/lib \
	-o kp_roctx_connector.so /autofs/nccs-svm1_home1/jjhu/crusher/kokkos-tools/src/kokkos-tools/profiling/roctx-connector/kp_roctx_connector.cpp -lroctx64
In file included from /autofs/nccs-svm1_home1/jjhu/crusher/kokkos-tools/src/kokkos-tools/profiling/roctx-connector/kp_roctx_connector.cpp:43:0:
/opt/rocm-5.2.0/roctracer/include/roctx.h:26:119: note: #pragma message: This file is deprecated. Use file from include path /opt/rocm-ver/include/ and prefix with roctracer
 #pragma message("This file is deprecated. Use file from include path /opt/rocm-ver/include/ and prefix with roctracer")
```

**Comment by dalg24** [comment]
Well that's awkward because according to the documentation https://docs.amd.com/bundle/ROCm-Profiling-Tools-User-Guide-v5.2/page/Kernel_Tracing.html that is still the header we are suppose to include...

> # ROCTracer API
> To use the ROCTracer API, you need the API header and dynamic library to link your application with ROCTracer:
> * API header: /opt/rocm-{version}/roctracer/include/roctracer.h
> * Dynamic library (.so): /opt/rocm-{version}/lib/libroctracer64.so

**Comment by dalg24** [comment]
I experimented with docker `rocm/dev-ubuntu-20.04` images.  I tried tags `4.5`, `5.0`, and `5.2` and all images had `/opt/rocm/include/roctracer/roctx.h`  so I suppose we don't need to worry too much about backwards compatibility.

**Comment by jrmadsen** [comment]
> Well that's awkward because according to the documentation https://docs.amd.com/bundle/ROCm-Profiling-Tools-User-Guide-v5.2/page/Kernel_Tracing.html that is still the header we are suppose to include...
> 
> > # ROCTracer API
> > To use the ROCTracer API, you need the API header and dynamic library to link your application with ROCTracer:
> > 
> > * API header: /opt/rocm-{version}/roctracer/include/roctracer.h
> > * Dynamic library (.so): /opt/rocm-{version}/lib/libroctracer64.so

Yeah, they did this for a lot of the packages (but _of course_ the documentation wasn’t updated). I suspect it’s bc ROCm is getting large enough they started having include path issues when things like AMD_INTERNAL_BUILD is defined.
