### ISSUE TITLE
SimpleKernelTimer: strange initialization message (`Example Library Initialized`)

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos-tools#148]
https://github.com/kokkos/kokkos-tools/blob/c901382c4c76b108e4e6d190e9236848dc764526/profiling/simple-kernel-timer/kp_kernel_timer.cpp#L120

It seems this name is not correct. It should say `SimpleKernelTimer loaded` or something like that. I suppose something along the following:
https://github.com/kokkos/kokkos-tools/blob/c901382c4c76b108e4e6d190e9236848dc764526/profiling/memory-events/kp_memory_events.cpp#L85

**Comment by vlkale** [comment]
Thanks, I will look into this.

@dalg24

**Comment by masterleinad** [comment]
Fixed in #150.
