### ISSUE TITLE
Need adequate documentation in README.md

### ISSUE THREAD

**Issue by vlkale** [kokkos/kokkos-tools#154]
# Problem

A typical README file https://en.wikipedia.org/wiki/README of (HPC) software contains information about (a) what the repository is for and (b) how use and develop the software. The README.md contains one sentence on what this repository is.  

Note that this github issue is not focused on improving _purely user-facing_ documentation, .e.g, tutorials on using Kokkos tools in computational science and engineering applications. Users often have questions such as how can I use the auto-tuning tools  kokkos on kokkosteam.github.com. A large amount of documentation  (though needing to be updated as features are added) is at 
https://github.com/kokkos/kokkos-tutorials/blob/main/LectureSeries/KokkosTutorial_07_Tools.pdf  and generally at kokkos.github.io. 

A description of each of the several connectors should be documented in one to two sentences. The methodology (standardized) to create a new connector should be briefly documented.

# Suggested Action

1. Develop an outline for documentation containing basic components of a typical README. In particular, need to explain why the repository exists, a vision and an outline of github issues. A rough timeline for availability will also help. 
2. Consult with Kokkos team on the documentation, obtaining informal feedback. 
3. Submit PR for new README, make changes as requested, get approved
4. Maintain README every month based on both user and developer feedback. 
5. Synch tutorials with README every three months to ensure up-to-date documentation in both information sources.

**Comment by vlkale** [comment]
Put in a new README based on the text from Kokkos-tools wiki, along with new alternate  build and run instructions with Cmake

**Comment by dalg24** [comment]
Did you mean to close it?  The README in the current develop branch has not been updated yet.

**Comment by vlkale** [comment]
Ah - this should  be reviewed and merged (need someone to merge for me since I don’t have rights to do merge). 

>

**Comment by vlkale** [comment]
Ping.

Looks like this hasn't been approved and merged into develop yet? Unless I am mistaken, I think there are no outstanding issues remaining here. 

The only other thing here - not listed by @dalg24 is that I think we may want to make notes in the Readme on notes running on common platforms, particularly for  Crusher and Perlmutter. 

@nmm0 I'm Noting here you and I (and maybe others interested) need to follow-up on the Kokkos tools documentation from the Kokkos tools Wiki with the new .rst, but that this might be done best as a separate (new) GitHub Issue in the Kokkos Tools repo.

**Comment by vlkale** [comment]
Ping. 

It looks like this hasn't been approved (and merged) into develop yet? I think there are no outstanding issues remaining here. 
Please let me know if I'm mistaken here.

The only other thing here - not listed by @dalg24 is that I think we may want to make notes in the Readme on notes running on common platforms, particularly for  Crusher and Perlmutter. 

@nmm0 I'm noting here you and I (and maybe others interested) need to follow-up on the Kokkos tools documentation from the Kokkos tools Wiki with the new .rst, but that this might be done best as a separate (new) GitHub Issue in the Kokkos Tools repo.


Thanks!
