### ISSUE TITLE
How to ues the Kokkos' kernel_logger in kokkos core code?

### ISSUE THREAD

**Issue by mingygit** [kokkos/kokkos-tools#164]
How to ues the Kokkos' kernel_logger in kokkos core code?

**Comment by vlkale** [comment]
Hi @mingygit, Thanks for checking this. You can find documentation for its use on the Kokkos Tools Wiki here:  https://github.com/kokkos/kokkos-tools/wiki/KernelLogger

The latest README (that has just been pushed to the develop branch of kokkos-tools) has high-level information on it. 

It will soon link to the above within it.

**Comment by vlkale** [comment]
> Hi @mingygit, Thanks for checking this. You can find documentation for its use on the Kokkos Tools Wiki here:  https://github.com/kokkos/kokkos-tools/wiki/KernelLogger
> 
> 
> 
> The latest README (that has just been pushed to the develop branch of kokkos-tools) has high-level information on it. 
> 
> 
> 
> It will soon link to the above within it. 

@mingygit i am closing this issue for now. Note I am working on new documentation for Kokkos Tools that will be accessible at kokkos.GitHub.io and I plan to have structure text formatted documentation.

There is a separate GitHub issue on this. 

Please provide feedback on the documentation if you have any.
