### ISSUE TITLE
Add profiling for atomics

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#19]
I'd like to know how much time is spent in atomic operations. Is there currently a way to discover this using the Kokkos profiling tools, and if not could this be added?

**Comment by nmhamster** [comment]
@stanmoore1 - this is really quite difficult to add because it has the potential to materially affect the optimization etc that is produced. You are probably better off trying to run this down via VTune etc. What platform do you want to perform this on?

**Comment by stanmoore1** [comment]
> What platform do you want to perform this on?

All of them :)

@nmhamster I'm sorry to hear that.

**Comment by mhoemmen** [comment]
This is kinda like asking to time some small subset of store instructions.  This stuff is super asynchronous.

**Comment by stanmoore1** [comment]
I'm not looking for razor sharp timings. I'd just like to know if/how much atomics killing my performance and if I need to rewrite the algorithm. But if it is not possible I understand.

**Comment by stanmoore1** [comment]
Closing since this doesn't seem feasible.
