### ISSUE TITLE
about passing metadata from a kokkos app to plugin

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos-tools#210]
Taking as example nvtx-connector, if i'm not mistaken, currently when a kokkos app calls `Kokkos::Profiling::pushRegion` the string argument is used by the plugin to call `nvtxRangeStartA`.

But let's just say, I'd like to call `nvtxRangeStartEx` so that I can specifiy e.g. the color, or any other field of the nvtx event attribute, and let's say I want to control these event "metadata" from the Kokkos App. 

I was thinking that maybe the plugin could have 2 "config" modes:
1. as it is right now (only the range label is used through  `nvtxRangeStartA`.
2. another mode, where each range could use additional data coming from kokkos app, which could pass e.g. a map<label, tuple<data1_t, data2_t>> this map would be filled by the application but used by the plugin, i.e. using  `nvtxRangeStartEx`
 
I can see that nvtx-focused-connector is using eventAttrib with `nvtxDomainRangeStartEx` but not controling the "color" field.
 
 Also, I can see that in Kokkos, in src/impl/Kokkos_Profiling.cpp there seem to be way to pass data to plugin, through `variable_metadata` but it is protected by `KOKKOS_ENABLE_TUNING`. 
Could it nevertheless be used to specify range color ?

Thanks in advance for any advice.

**Comment by vlkale** [comment]
Thanks for posting. What kind of data type is element 1 and element 2 in the hashmap? Are these floats or primitive types? Or, are they by chance more complex classes?This could be done, but it would probably need some non-trivial reworking and rewiring of the Kokkos Tools interface including src/impl/Kokkos_Profiling.cpp. If you tell me the kind of application data, I can try to hone in on at least a basic solution for the 2nd mode you describe. Let me know.

**Comment by pkestene** [comment]
Ok, let me clarify:

i was thinking that, e.g. nvtx-connector could expose a payload class that allows the user to specify the "color" field of the nvtx event attribute. So somewhere in the user kokkos application code, instead of calling directly:
```c++
Kokkos::Profiling::ScopedRegion myprof("Region1");
```
the use could define at custom compound class that contains a ScopeRegion object, plus additionnal data (here a "color", .e. a uint32_t) and the constructor of this compound class would initialize the ScopedRegion with the label, and also add color to a static `std::map<string,uint32_t> plugin_payload` for mapping the region label string to a color (uint32_t). So dynamically this map would be enriched, each time a new ScopedRegion is created. Maybe that this static map should be stored outside of the class, and constructed right before the plugins are loaded, so that a pointer or reference to this static "map" would be passed to nvtx-connector (any other plugin would just ignore this specific map, but each plugin could expose a different admissible payload)

**Comment by jrmadsen** [comment]
There is support for a tool accepting command line arguments, which would effectively allow you to pass information to the tool at startup

**Comment by pkestene** [comment]
@jrmadsen 
so, if I follow, you're suggesting that instead of contructing payload data in the user app, just provide payload data from a file, and pass that file via command line, at application startup to transfer information to the plugin. I would prefer do it inside the application, but if there is already support for that why not.
So we only need to slightly modify nvtx-connector to accept payload data.

**Comment by jrmadsen** [comment]
> I would prefer do it inside the application

Well, technically a tool with the `kokkosp_parse_args(int argc, char** argv)` function just gets the command line from `Kokkos::initialize(argc, argv);` in the application so if you’d prefer to do it in the app, you could always make a copy of the argv array, insert a `--kokkos-tools-args=“…”` with whatever info you want, and pass the modified argument count and array to `Kokkos::initialize`

See https://github.com/kokkos/kokkos/pull/3627 for details.

**Comment by jrmadsen** [comment]
There’s also the metadata interface:

https://github.com/kokkos/kokkos/blob/1a3ea28f6e97b4c9dd2c8ceed53ad58ed5f94dfe/core/unit_test/tools/printing-tool.cpp#L153

https://github.com/kokkos/kokkos/blob/1a3ea28f6e97b4c9dd2c8ceed53ad58ed5f94dfe/core/unit_test/tools/TestAllCalls.cpp#L60

**Comment by pkestene** [comment]
ok thanks, that is helpfull; i'll take a look

**Comment by vlkale** [comment]
@pkestene Did the metadata interface @jrmadsen mentioned help? 

Was this issue resolved for you?

**Comment by pkestene** [comment]
yes, you can close. thank you.

**Comment by vlkale** [comment]
No problem, and thank you for putting forth your question here.
