### ISSUE TITLE
Some small typos in the wiki

### ISSUE THREAD

**Issue by davis-matthew** [kokkos/kokkos-tools#214]
I don't know of any way to create a pull request for wiki pages, so I guess an issue works?

Here's a diff of some small typos/grammar/etc. found while I read through the wiki pages.

https://github.com/kokkos/kokkos-tools/compare/master...davis-matthew:kokkos-tools:master?expand=1

**Comment by dalg24** [comment]
I applied the changes** on your behalf.

** except the one in `Profiling-Hooks.md`.  Was that one only a double space fix?

**Comment by davis-matthew** [comment]
Yes, that file can be ignored. Thank you for merging the changes in

**Comment by vlkale** [comment]
@davis-matthew Your edits are much appreciated . Yes, providing a diff is probably the easiest way to provide contributions or fixes to the Wiki. 

@dalg24 Thanks for this.
