### ISSUE TITLE
Weird (buggy?) behavior from the space-time-stack tool

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#22]
I'm seeing some perplexing behavior from the `space-time-stack` tool. The d_sorted (particle:sorted) View in my code has no other references (reference count = 1 always) and is periodically reallocated:
<pre>
    if (d_particles.dimension_0() > d_sorted.dimension_0()) {
      d_sorted = t_particle_1d("particle:sorted",d_particles.dimension_0());
    }
</pre>
I can't understand how, but the d_sorted (particle:sorted) view appears twice in the `space-time-stack` tool output list for CUDA:
<pre>
MPI RANK WITH MAX MEMORY: 0
MAX BYTES ALLOCATED: 8574610364
HOST ALLOCATIONS:
================
  19.4% particle:particles_mirror
  2.3% grid:cells_mirror
  1.2% grid:cinfo_mirror
  0.7% particle:mlist_mirror
  0.2% emit/face:tasks_mirror
  0.2% collide:vremax_mirror
  0.2% collide:remain_mirror
  0.2% thermal/grid:vector_grid_mirror
  0.2% thermal/grid:tally_mirror
CUDA ALLOCATIONS:
================
  19.4% particle:sorted
  19.4% particle:particles
  19.4% particle:sorted
  11.5% particle:plist
  2.3% grid:cells
  1.2% grid:cinfo
  0.7% particle:mlist
  0.2% emit/face:tasks
  0.2% collide:vremax
  0.2% collide:remain
  0.2% thermal/grid:vector_grid
  0.2% thermal/grid:tally
</pre>

If I first destroy the d_sorted view like this:
<pre>
    if (d_particles.dimension_0() > d_sorted.dimension_0()) {
      d_sorted = t_particle_1d();
      d_sorted = t_particle_1d("particle:sorted",d_particles.dimension_0());
    }
</pre>
then d_sorted isn't listed twice in the CUDA output, but the overall high water mark doesn't change, and another copy of the particle:particles_mirror host view appears!
<pre>
MPI RANK WITH MAX MEMORY: 0
MAX BYTES ALLOCATED: 8638309940
HOST ALLOCATIONS:
================
  19.3% particle:particles_mirror
  19.3% particle:particles_mirror
  2.3% grid:cells_mirror
  1.2% grid:cinfo_mirror
  0.7% particle:mlist_mirror
  0.2% emit/face:tasks_mirror
  0.2% collide:vremax_mirror
  0.2% collide:remain_mirror
  0.2% thermal/grid:vector_grid_mirror
  0.2% thermal/grid:tally_mirror
CUDA ALLOCATIONS:
================
  19.3% particle:particles
  19.3% particle:sorted
  12.1% particle:plist
  2.3% grid:cells
  1.2% grid:cinfo
  0.7% particle:mlist
  0.2% emit/face:tasks
  0.2% collide:vremax
  0.2% collide:remain
  0.2% thermal/grid:vector_grid
  0.2% thermal/grid:tally
</pre>

@ibaned any ideas?

**Comment by ibaned** [comment]
Hmm I think I know the answer. This line of code:
```cpp
d_sorted = t_particle_1d("particle:sorted",d_particles.dimension_0());
```
Actually breaks down into the following order of events:
```cpp
auto d_sorted_new = t_particle_1d("particle:sorted",d_particles.dimension_0());
//at this point in time, two allocations exist called "particle:sorted"
d_sorted = d_sorted_new; // this line destroys the older of the two
```
So in this case the tool is correct, it uses twice the memory for a brief moment and your workaround does reduce high water mark memory usage.

**Comment by stanmoore1** [comment]
Actually it *doesn't* reduce the high water mark, at least not by much. The view in question is about 1.5 GB, so the high water mark should really drop.

**Comment by stanmoore1** [comment]
But a new host view appears, which wasn't there before, and that cancels out the change in memory. The % of memory in CUDA drops from ~75% to ~50%. However, if I use the memory-usage tool, the CUDA and Host high water marks remain nearly the same. I think this is a bug...

**Comment by ibaned** [comment]
The high water mark bytes did change, and what seems strange to me is that it increased in size. The high water mark point in time has almost certainly changed, and the double `particle:particles_mirror` on the host is now the big deal... do you get consistent reports if you run this program several times?

**Comment by stanmoore1** [comment]
The high water mark only changed by 0.06 GB, while the size of the particle arrays is about 1.5 GB.

**Comment by stanmoore1** [comment]
If I run the program several times the high water mark jumps around a little, but the view list stays the same:

<pre>
MPI RANK WITH MAX MEMORY: 0
MAX BYTES ALLOCATED: 8572784844
HOST ALLOCATIONS:
================
  19.4% particle:particles_mirror
  19.4% particle:particles_mirror
  2.3% grid:cells_mirror
  1.2% grid:cinfo_mirror
  0.7% particle:mlist_mirror
  0.2% emit/face:tasks_mirror
  0.2% collide:vremax_mirror
  0.2% collide:remain_mirror
  0.2% thermal/grid:vector_grid_mirror
  0.2% thermal/grid:tally_mirror
CUDA ALLOCATIONS:
================
  19.4% particle:particles
  19.4% particle:sorted
  11.5% particle:plist
  2.3% grid:cells
  1.2% grid:cinfo
  0.7% particle:mlist
  0.2% emit/face:tasks
  0.2% collide:vremax
  0.2% collide:remain
  0.2% thermal/grid:vector_grid
  0.2% thermal/grid:tally


MPI RANK WITH MAX MEMORY: 0
MAX BYTES ALLOCATED: 8638320588
HOST ALLOCATIONS:
================
  19.3% particle:particles_mirror
  19.3% particle:particles_mirror
  2.3% grid:cells_mirror
  1.2% grid:cinfo_mirror
  0.7% particle:mlist_mirror
  0.2% emit/face:tasks_mirror
  0.2% collide:vremax_mirror
  0.2% collide:remain_mirror
  0.2% thermal/grid:vector_grid_mirror
  0.2% thermal/grid:tally_mirror
CUDA ALLOCATIONS:
================
  19.3% particle:particles
  19.3% particle:sorted
  12.1% particle:plist
  2.3% grid:cells
  1.2% grid:cinfo
  0.7% particle:mlist
  0.2% emit/face:tasks
  0.2% collide:vremax
  0.2% collide:remain
  0.2% thermal/grid:vector_grid
  0.2% thermal/grid:tally

END KOKKOS PROFILING REPORT.
</pre>

**Comment by ibaned** [comment]
Ah, okay, this makes more sense. The "jumping around" explains why the high water mark bytes were greater after your change compared to before; there is a bit of non-determinism in your program. In fact, the first snapshot of the two you just posted, `8572784844`, is less than the original snapshot at the top of this issue. I don't see a clear bug in the tool at this point; your new high water snapshot is at a different point in the program and it looks like `particle:particles_mirror` has the same resize issue as the last View that you fixed. This is basically the new "tallest tent pole" as it were.

**Comment by stanmoore1** [comment]
So why is a host view now duplicated if I only change a device view? Why wasn't the host view listed in the first case? It was way bigger than any of the other views listed.

**Comment by stanmoore1** [comment]
And why didn't the high water mark go down now that I deallocated a device view?

**Comment by ibaned** [comment]
> So why is a host view now duplicated if I only change a device view? Why wasn't the host view listed in the first case? It was way bigger than any of the other views listed.

Because these are two different points in time. Its not the same point in time; for each run the tool will pick the max-usage point in time. So I think your program is like:

```
001: // first source (many lines of code)
100: d_sorted = t_particle_1d("particle:sorted",d_particles.dimension_0());
101: // second source (many lines of code)
200: h_mirror = h_mirror_type("particle:particles_mirror", size);
201: // third source (many lines of code)
```

At first, lines `100` and `200` were the two points of highest memory usage, both used almost the same amount, and due to some non-determinism, different runs would peak at one or the other. Now that you fixed line `100`, line `200` is now the point of max memory usage.

> And why didn't the high water mark go down now that I deallocated a device view?

Due to the non-determinism. Your last two snapshots from different runs of the same code show this:
```
original code, at line 100 before fixing it: 8574610364
new code, after fixing line 100, run 1:      8638320588
new code, after fixing line 100, run 2:      8572784844
```
Although `run 1` looks like it took more memory, `run 2` shows that the memory actually went down, in one of the non-deterministic combinations.

**Comment by stanmoore1** [comment]
According to `space-time-stack` 56% of 8638320588 bytes is used for CUDA = 4613 MB. But according to the `memory-usage` tool, the CUDA high water mark for Kokkos Views on the device is 6172.9 MB (stays constant over different runs, non no-determinism) , which is 1500 MB different. Both can't be right.

**Comment by ibaned** [comment]
This is probably due to the fact that `space-time-stack` treats both spaces as one total? if `memory-usage` treats them as separate total (I think it does), then it makes sense that they're different. And I still agree that separate totals is a better implementation, making that change is on my todo list.

**Comment by stanmoore1** [comment]
Are you saying that the list of views from `space-time-stack` are only the views allocated when the high water mark was captured, and not the biggest views by size over the whole run?

**Comment by ibaned** [comment]
> Are you saying that the list of views from space-time-stack are only the views allocated when the high water mark was captured, and not the biggest views by size over the whole run?

Correct, they are the views that existed at the point in time when memory use was the highest.

**Comment by stanmoore1** [comment]
> This is probably due to the fact that space-time-stack treats both spaces as one total? 

I could see how that makes sense...

**Comment by stanmoore1** [comment]
>Correct, they are the views that existed at the point in time when memory use was the highest.

Might be good to put that info in the output, like "memory snapshot at time of high water mark". I thought it was a list of the largest views over the whole run.

**Comment by ibaned** [comment]
> Might be good to put that info in the output, like "memory snapshot at time of high water mark". I thought it was a list of the largest views over the whole run.

Yep, will do.

**Comment by stanmoore1** [comment]
So I think I have my questions answered, closing this ticket.

**Comment by stanmoore1** [comment]
@ibaned I do think this `space-time-stack` tool is useful... just trying to understand it.

**Comment by ibaned** [comment]
Yep, no worries. It needs to be clear and intuitive to users :)
I'm coding the fixes now and a PR will be up today.
