### ISSUE TITLE
Incorrect link in the wiki page to nvtxConnector wiki

### ISSUE THREAD

**Issue by zhangchonglin** [kokkos/kokkos-tools#230]
In the [ wiki page](https://github.com/kokkos/kokkos-tools/wiki), the link provided to the `nvtxConnector` is pointing to the wiki page of `rocmConnector`, in [this part ](https://github.com/kokkos/kokkos-tools/wiki#vendor-provided)of the page.

```
 [nvtxConnector](https://github.com/kokkos/kokkos-tools/wiki/rocmConnector)
```
Correct link should be:
```
 [nvtxConnector](https://github.com/kokkos/kokkos-tools/wiki/nvtxConnector)
```

**Comment by vlkale** [comment]
Fixed. Thanks @zhangchonglin!
