### ISSUE TITLE
wiki pages have broken links to tools

### ISSUE THREAD

**Issue by gliga** [kokkos/kokkos-tools#232]
wiki pages (e.g., https://github.com/kokkos/kokkos-tools/wiki/SimpleKernelTimer) have links that are not pointing to a proper place any more, as some directories have been renamed. Also several links point to `master` rather than `develop`.

Attached is the patch to fix the links.
Unfortunately GitHub does not support PRs for the wiki pages, so I could not send one. (And also `.patch` extension is not supported on GitHub so sending as `.txt`.)

[wiki.txt](https://github.com/kokkos/kokkos-tools/files/13933100/wiki.txt)

**Comment by vlkale** [comment]
Thanks @gliga! I have looked at your .txt file for wiki diff for this PR. I have put in fixes I saw.

I also put in the link for the nvtx-connector and made minor wording changes to present the references for the nvtx-connector. 

Will you tell me if all looks good?

**Comment by gliga** [comment]
Hello, thanks for addressing my comments.  There are still some pages that do not use correct URL, e.g., https://github.com/kokkos/kokkos-tools/wiki/KernelFilter

**Comment by vlkale** [comment]
@gliga  Sorry for the delay in replying. I had fixed this and just now double checked all links to repos. 

I will close this for now, and please let me know if there are any other comments or proposed fixes on the wiki. Thanks!

**Comment by gliga** [comment]
Thanks
