### ISSUE TITLE
I can't get demangled names from nvtx-connector

### ISSUE THREAD

**Issue by Shihab-Shahriar** [kokkos/kokkos-tools#263]
Hi,

I went through the wiki for nvtx-connector, I get this message after I launch the profiler, so I assumed things are working fine

```
KokkosP: NVTX Analyzer Connector (sequence is 0, version: 20211015)  
```

Unfortunely, the names are all still mangled. I am using cuda 12.4.1 (and nsight-compute built-in), kokkos 4.3.01 and kokkos-tools' latest from master branch.

**Comment by vlkale** [comment]
@Shihab-Shahriar Thanks for posting. You say that you are using kokkos-tools latest from the _master_ branch. You should use the _develop_ branch, if you are not doing that (I have tried to make this clearer in the documentation). Can you confirm that you are indeed using the develop branch of kokkos-tools?

**Comment by Shihab-Shahriar** [comment]
I wasn’t.  I’ll let you know how it turns out. 

Thanks for your prompt reply.

**Comment by Shihab-Shahriar** [comment]
Unfortunately, it isn't working even on latest `develop` branch. 

To give you the exact details, I found the absolute path using `realpath` command, did `export KOKKOS_TOOLS_LIBS=/the/path/to/libkp_nvtx_connector.so`, and launched nsight compute like so:

`ncu -o prof ./app ~/config.yaml`

Is there anything else I should be doing?

**Comment by vlkale** [comment]
I don't think there is a problem with the nvtx-connector (I have tested successfully on Perlmutter a couple months ago). 
Rather, it is the way ncu is called, and given that, my documentation for nvtx-connector needs to be updated. 

Specifically, I think ncu needs to have nvtx marker tracing turned on. Looking at https://docs.nvidia.com/nsight-compute/ for NSIGHT Compute for the latest information, I think you also have to pass the correct flags to `ncu`. In particular, you need a flag `--nvtx`. I think you can also use `-t nvtx` but this may not be supported now in the latest version looking at the documentation. 

A couple of other notes: 

* Now, If there is a problem with the nvtx-connector library code itself: The only thing I can think of is that this has to do with the nvToolsExt.h in the nvtx-connector needing to be changed to 

* Thanks for telling me your setup. I assume you are running with the serial+CUDA backend of Kokkos 4.3.1. Did you also set  -DKokkos_DIR=/path/to/your/Kokkos-build when you built Kokkos Tools? 

A couple of general comments: 

* Though these slides are from July 2023, look here for better explanation: 
https://doku.lrz.de/files/29609547/36864865/1/1689006900610/Intro_Nsight+Systems.pdf

* NVIDIA has rapidly evolved their profiling tools over years (you used to just have nvprof for profiling), and it is important to also use the latest documentation for actually running `ncu`, `https://docs.nvidia.com/nsight-compute/`

Let me know if the above doesn't help still. I will update the documentation to make it clear one needs to also make ncu capture nvtx markers.

**Comment by Shihab-Shahriar** [comment]
Hi,

Thank you, I can now see my assigned names thanks to the --nvtx marker. Although the kernel name now appears like:

`my_kernel_name/_ZN6Kokkos4ImplL36cuda_parallel_launch_constant_memoryINS0_11ParallelForIZ.....`

I.e. my given name+ "/" + lots of other stuff. 

Not sure if this can be avoided, but this will do for now.

Thanks again for your help.

**Comment by vlkale** [comment]
Yes, I am not entirely sure how that can be avoided. 

No problem, and let me know if you need anything else here. 

FYI, I have updated the documentation on the nvtx-connector on the Kokkos Tools wiki page to make its use with ncu more clear.
