### ISSUE TITLE
Add times to breakdown in space-time-stack

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#30]
@ibaned it would be really nice if `space-time-stack` had actual times in the breakdown instead of just relative percentages plus the total time. This would make it much easier to compare different runs that have a different total time. Right now I have to post-process the results by taking the total time and multiplying by all the percentages to get the breakdown times.

**Comment by ibaned** [comment]
@stanmoore1 I just pushed this change to master, let me know if its what you want

**Comment by stanmoore1** [comment]
@ibaned thanks! Closing #30.
