### ISSUE TITLE
space-time-stack erroring out due to Kokkos version

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#32]
I'm getting a cryptic error from space-time-stack:

```
kokkosp_init_library: version 20171029 != 20150628
*** Process received signal ***
Signal: Aborted (6)
```

Looks like it is coming from https://github.com/kokkos/kokkos-tools/blob/master/src/tools/space-time-stack/kp_space_time_stack.cpp#L533

```c++
  if (version != 20150628) {
    std::cerr << "kokkosp_init_library: version " << version << " != 20150628\n";
    abort();
  }
```

Can this check be relaxed or updated?

**Comment by stanmoore1** [comment]
@ibaned

**Comment by nmhamster** [comment]
@stanmoore1 - did you recompile?

**Comment by ibaned** [comment]
@stanmoore1 @nmhamster I put a hardcoded check for this exact version into the profiling tool. It should be relaxed in some way. If we can assume the function signatures will always be backwards compatible (i.e. no changes to the arguments of hooks that are already defined), then there isn't much need for this check. The Kokkos library will only load the hooks it knows about and leave it at that. Kokkos also checks whether the profiling library supports each hook, so its pretty flexible. I think I'll just remove this check, I was being overly cautious during early development.

**Comment by stanmoore1** [comment]
@ibaned sounds good, thanks

**Comment by stanmoore1** [comment]
@ibaned should I remove this check and submit a PR?

**Comment by ibaned** [comment]
@stanmoore1 I think I removed it a week or two ago...
https://github.com/kokkos/kokkos-tools/commit/d4bd6216c196b761c2e77f254b23da6843dd569a
I forgot this issue was here.
It should be fixed, if not please comment.

**Comment by stanmoore1** [comment]
Ah great, I didn't see that, thanks
