### ISSUE TITLE
Add "percent time in Kokkos parallel constructs" to region stats in space-time-stack

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos-tools#37]
@csiefer2

**Comment by ibaned** [comment]
@csiefer2 I just did this! Please look at the `TOP-DOWN` report, the second percentage is hopefully what you're looking for.

**Comment by csiefer2** [comment]
Haven't tried it yet.  I'll give it a go next week and open a new issue if there are problems.

**Comment by csiefer2** [comment]
It does what I need!  Thanks @ibaned !!!
