### ISSUE TITLE
kernel names in nvprof

### ISSUE THREAD

**Issue by jacobmerson** [kokkos/kokkos-tools#55]
I am wondering how to properly use the nvprof-connector, so that the kokkos kernel names show up in demangled form in the visual debugger.

**Comment by vlkale** [comment]
@jacobmerson Thanks for your question. I assume the Kokkos user's workflow for the visual debugger is something similar to that of HPCToolkit, given my knowledge of visual debuggers for parallel programming available. 

This isn't really a Kokkos Tools issue. Rather, it is a matter of the visual debugger supporting the Kokkos Tools nvtx-connector's hooks. The nvtx-connector already recognizes and processes the Kokkos kernel names. Your question is addressed given your visual debugger recognizes hooks for nvtx-connector. 

I have put a comment in Kokkos Tools Wiki documentation for nvtx-connector which briefly mentions the of external visual profiling and debugging tools, given one uses the nvtx-connector. I have noted what I have said in the above paragraph.
