### ISSUE TITLE
Update simple kernel timer to write output to text file

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos-tools#72]
Tool should send output to `<hostname>.<process id>.simple_kernel_timer` instead of default stdout.

**Comment by DavidPoliakoff** [comment]
Is this feedback from a user? And are we breaking anybody's current expectations? I'd prefer setting this through an environment variable or build option, with the default remaining unchanged, unless this comes from one of the code teams.

**Comment by jeffmiles63** [comment]
So, this issue originated from a discussion in a Kokkos tutorial session.  I believe the larger problem is the inconsistency with which the kokkos provided tools report information.  Whether it is a build option or additional environment variable is fine, as long as the behavior is consistent across all of the tools.

**Comment by crtrott** [comment]
Actually Jeff mischaracterized a bit. I want the tool to write a text file not a binary file. I think the space savings are just not worth the hassle with the stupid reader. This has been annoying me since we wrote this tool in the first place, and I have not seen a single person who thought it is a brilliant idea that the output file is binary ...

**Comment by DavidPoliakoff** [comment]
Yeah, having the "simple" tool not write out text is aggravating. I'll think on this a bit. I'm leaning towards the answer:

Short term: update simple-kernel-timer to write a (text) file as the default
Longer term: standards for how tools should output their files, update all existing tools

**Comment by jrmadsen** [comment]
> Longer term: standards for how tools should output their files, update all existing tools

Cereal is a good header-only serialization library to write a JSON file. Also supports XML and binary archives but JSON is just as easy to read as a regular text file and soo easy to postprocess in Python. I say just add cereal as git submodule and do a git submodule update in CMake if it isn't already checked out so it's basically an invisible dependency to the casual observer.

**Comment by vlkale** [comment]
I believe PR #235 helps to address this Github Issue.

**Comment by vlkale** [comment]
@jeffmiles63 I am closing this as this #235 should now address this. Please let me know in case there are other questions here.
