### ISSUE TITLE
HWM for GPU memory

### ISSUE THREAD

**Issue by zackgalbreath** [kokkos/kokkos-tools#79]
If I understand #21 correctly, it looks like the HWM tool reports on CPU memory usage (not GPU).

Is there any tool available in this repo that can help me get the HWM for GPU memory used by a program?

**Comment by DavidPoliakoff** [comment]
@zackgalbreath , if you're interested in the memory usage of `Kokkos::View`'s it's pretty easy with the space time tool in Kokkos, but we don't include a tool for total GPU memory usage. If that's of interest we could probably put one together pretty easily

**Comment by zackgalbreath** [comment]
Thanks for the quick reply! I'll re-open this issue if we decide to pursue a more general GPU memory tracker.

**Comment by crtrott** [comment]
The MemoryUsage tool gives a timeline for memory usage in each memory space.

**Comment by jrmadsen** [comment]
@zackgalbreath The third-party tools have methods for wrapping both malloc/free and cudaMalloc/cudaFree if you decide to go that route and are running on Linux. In particular, two third-party tools that support kokkos-tools with this capability are Caliper and timemory. @DavidPoliakoff could help with using Caliper, I can help you with timemory. Caliper is a more established package and would probably be a better choice if you want something simple. timemory is a newer package designed as an API for building instrumentation tools and, while it has a "malloc_gotcha" component you can just use, it will also let you build your own component(s) to collect exactly what you want, e.g. frequency of calls, how long it took to execute alloc/free, etc. -- and by doing so, add support for tracking statistics, outputting in JSON, XML, and/or text, etc.

**Comment by jrmadsen** [comment]
And, actually, I like the idea of adding a timeline collection mode in addition to the hierarchical and flat profile collection modes. I will add that capability in the next release.
