### ISSUE TITLE
Provide MPI-aware versions of certain kokkos-tools

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos-tools#8]
When I am running on more than 500,000 MPI ranks, I don't appreciate all the ranks printing out this half a million times to stdout:
 
KokkosP: Library Loaded: ./kokkos-tools/src/tools/memory-hwm/kp_hwm.so 
KokkosP: Finalization of profiling library.
KokkosP: High water mark memory consumption: 420856 kB

Also opening and writing to half a million files for `memory-events` or `memory-usage` hammers the I/O system.
 
I know Kokkos and kokkos-tools don't know about MPI, but it would be useful if we could limit this output to MPI rank 0 and print out total min, average, and max memory consumption.

**Comment by crtrott** [comment]
Actually Kokkos-Tools are allowed to know about MPI. We (or you) could just write a variant of those tools which is MPI aware and consolidates output.

**Comment by ibaned** [comment]
Maybe this issue becomes "write MPI-aware versions of certain kokkos-tools" ?

**Comment by stanmoore1** [comment]
> Maybe this issue becomes "write MPI-aware versions of certain kokkos-tools" ?

Yes please consider this a feature request.

**Comment by ibaned** [comment]
I'm guessing at a minimum the high-water-mark one is desired:
 - [ ] memory-hwm

**Comment by ibaned** [comment]
`memory-hwm` is done in PR #13. @stanmoore1 let me know your priority order of other tools.

**Comment by stanmoore1** [comment]
@ibaned thanks, I'll try it out when I get a chance.

**Comment by stanmoore1** [comment]
@ibaned I tried the MPI-aware version of `memory-hwm` and it works good. The `space-time-stack` tool is also a good MPI-aware profiling tool.

**Comment by stanmoore1** [comment]
The `space-time-stack` tool is working well for me for large MPI jobs, closing this ticket.
