### ISSUE TITLE
this project has no license

### ISSUE THREAD

**Issue by jeffhammond** [kokkos/kokkos-tools#84]
Please add a license to this project.  Thanks.

**Comment by DavidPoliakoff** [comment]
Good catch. I'll do that Monday

>

**Comment by DavidPoliakoff** [comment]
"Monday." But we do have a license now, thanks for reminding us

**Comment by jeffhammond** [comment]
Every week has a Monday in it, so I'm confident that it will be done by Monday.

**Comment by vlkale** [comment]
@jeffhammond  This has been done now and merged into develop.
