### ISSUE TITLE
Documentation for writing a Kokkos connector?

### ISSUE THREAD

**Issue by tpatki** [kokkos/kokkos-tools#92]
@DavidPoliakoff 

@zfrye-llnl and I are thinking of writing a Variorum connector for Kokkos (https://github.com/LLNL/variorum). Is there any documentation on how to write one (or which functions: initialize/finalize, push/pop, begin/end_parallel_for are mandatory)?

**Comment by DavidPoliakoff** [comment]
@tpatki 
Unfortunately, there's not great formal documentation on that, which I'll of course make a note of. Typical practice is to copy/paste something existing. As to what's required, only init and finalize are required. The full set of options is available here https://github.com/kokkos/kokkos-tools/wiki/Profiling-Hooks . I'm so happy you're taking a look at this, I'm excited to play with Variorum

**Comment by DavidPoliakoff** [comment]
@zfrye-llnl : sorry that I missed you in the last message. You might also want to check out kokkos/kokkos#2422 , in which we're adding an autotuning extension to this interface. If it's feasible it might be interesting to develop a tool to minimize power without hurting performance, or things of that general flavor of optimization. That stuff is _utterly_ undocumented for the moment, so we'd need to collaborate, but I'd be happy to look at it with the two of you.

**Comment by vlkale** [comment]
I would like to promote this github issue up as a priority for documentation of Kokkos Tools (using the new restructuredText format). 

Documentation of a Kokkos connector will be helpful for the ever-increasing vendor and open-source HPC tools available. In particular, this will be useful for autotuning tools available within the DoE along with new profiling and debugging tools available (in the last year) on leadership class supercomputers within the DoE.

**Comment by vlkale** [comment]
Now part of the Kokkos Tools tutorial.

**Comment by vlkale** [comment]
See the NERSC 2024 tutorial presentation on Kokkos to see the documentation / slides. I think the slides adequately provide information. 

If there is any other information anyone would like on documentation writing a Kokkos Tools connector, please feel free to request to reopen. 

Note this is an advanced topic and wouldn't be part of basic Kokkos Tools user documentation, which is a priority.
